Repository zanfranceschi/rinha-de-backend-2023-q3, pull requests merged in 2023-08, with the labels that each got.

#121 Submission by brunoborges
  participantes/brunoborges/ddl.sql
  participantes/brunoborges/docker-compose-arm.yml
  participantes/brunoborges/docker-compose.yml
  participantes/brunoborges/nginx.conf
  participantes/brunoborges/run.sh
Labels: needs change

#119 Check de consistência de dados
  stress-test/user-files/simulations/rinhabackend/RinhaBackendSimulation.scala
Labels: needs test

#126 instrucoes para rodar a versao de albertosouza
  participantes/alberto_souza/README.md
  participantes/alberto_souza/docker-compose.yaml
  participantes/alberto_souza/infra/nginx/Dockerfile
  participantes/alberto_souza/infra/nginx/loadbalancer/conf.d/rinhadebackend.conf
  participantes/alberto_souza/infra/nginx/loadbalancer/include/proxy.conf
  participantes/alberto_souza/infra/nginx/nginx.conf
Labels: needs change

#173 Juro que é a ultima coisa que eu vou mecher :D
  participantes/krymancer/init.sql
  participantes/krymancer/nginx.conf
Labels: ajuste em submissão

#214 o Destemido Gopher
  participantes/true_eduardo/README.md
  participantes/true_eduardo/docker-compose.yml
  participantes/true_eduardo/initdb.sql
  participantes/true_eduardo/nginx.conf
Labels: submissão nova

#213 Add insalubre
  participantes/insalubre/README.MD
  participantes/insalubre/docker-compose.yml
  participantes/insalubre/nginx.conf
  participantes/insalubre/schema.sql
Labels: submissão nova

#212 dscamargo: update files
  participantes/dscamargo/docker-compose.yml
  participantes/dscamargo/scripts/keydb/keydb.conf
  participantes/dscamargo/scripts/nginx/nginx.conf
  participantes/dscamargo/scripts/postgres/init.sql
  participantes/dscamargo/scripts/postgres/postgresql.conf
Labels: ajuste em submissão

#211 Rinha com Lean4
  participantes/sofia_aripiprazole/README.md
  participantes/sofia_aripiprazole/docker-compose.yml
  participantes/sofia_aripiprazole/init.sql
  participantes/sofia_aripiprazole/nginx.conf
Labels: submissão nova

#208 Outra versão Bash
  participantes/leandronsp-bash/README.md
  participantes/leandronsp-bash/docker-compose.yml
  participantes/leandronsp-bash/init.sql
  participantes/leandronsp-bash/nginx.conf
  participantes/leandronsp-bash/postgresql.conf
Labels: submissão nova

#205 API in pure C
  participantes/felipemarkson/README.md
  participantes/felipemarkson/deletevolume.sh
  participantes/felipemarkson/docker-compose.yml
  participantes/felipemarkson/nginx.conf
Labels: submissão nova

#108 Adicionar participação de andre237
  participantes/andre237/README.md
  participantes/andre237/docker-compose.yml
  participantes/andre237/nginx.conf
Labels: needs change, submissão nova

#169 h4nkb31f0ng: atualização
  participantes/h4nkb31f0ng/README.md
  participantes/h4nkb31f0ng/docker-compose.yml
  participantes/h4nkb31f0ng/scripts/keydb/keydb.conf
  participantes/h4nkb31f0ng/scripts/nginx/nginx.conf
  participantes/h4nkb31f0ng/scripts/postgres/postgresql.conf
  participantes/h4nkb31f0ng/scripts/postgres/schema.sql
Labels: ajuste em submissão, manualmente validado

#170 vhogemann - F# NET 7.0
  participantes/vhogemann/README.md
  participantes/vhogemann/bootstrap.sql
  participantes/vhogemann/docker-compose.yml
  participantes/vhogemann/nginx.conf
Labels: submissão nova, manualmente validado

#174 Update config files
  participantes/lpicanco/schema.sql
Labels: ajuste em submissão

#175 Submissão danielfireman rinha-be-2023-q3
  participantes/danielfireman/README.md
  participantes/danielfireman/docker-compose.yml
  participantes/danielfireman/nginx.conf
Labels: submissão nova

#177 update rinha files
  participantes/isaacnborges/docker-compose.yml
  participantes/isaacnborges/nginx.conf
  participantes/isaacnborges/script.sql
Labels: ajuste em submissão

#180 Add matheuslc
  participantes/matheuslc/README.md
  participantes/matheuslc/docker-compose.yml
  participantes/matheuslc/init.sql
  participantes/matheuslc/nginx.conf
  participantes/matheuslc/postgresql.conf
Labels: submissão nova

#183 Padronizando compose
  participantes/davidlins/docker-compose.yml
Labels: ajuste em submissão

#190 Added new project to the competition
  participantes/Bandolin_simplified_api/README.md
  participantes/Bandolin_simplified_api/docker-compose.yml
  participantes/Bandolin_simplified_api/my.cnf
  participantes/Bandolin_simplified_api/nginx.conf
  participantes/Bandolin_simplified_api/www.conf
Labels: submissão nova

#191 adicionando health check para o banco
  participantes/LuisKpBeta/docker-compose.yml
Labels: ajuste em submissão

#193 Inclusão participante ftsuda
  participantes/ftsuda/README.md
  participantes/ftsuda/docker-compose.yml
  participantes/ftsuda/nginx.conf
  participantes/ftsuda/postgresql.conf
Labels: submissão nova

#201 Tinha colocado a porta errada no nginx.conf
  participantes/andrelsmelo/nginx.conf
Labels: ajuste em submissão

#204 oliveigah: docker-compose tweaks
  participantes/oliveigah/README.md
  participantes/oliveigah/docker-compose.yml
  participantes/oliveigah/nginx.conf
Labels: ajuste em submissão

#171 +boaglio: Java stack (Spring Boot com WebFlux + MongoDB Reactive)
  participantes/boaglio/README.md
  participantes/boaglio/infra/Dockerfile
  participantes/boaglio/infra/docker-compose.yml
  participantes/boaglio/infra/nginx.conf
Labels: needs change, submissão nova

#125 uasouz (v_hadara) submission
  participantes/uasouz/README.md
  participantes/uasouz/docker-compose.yml
  participantes/uasouz/nginx.conf
  participantes/uasouz/run.sh
Labels: submissão nova, manualmente validado
